### ISSUE TITLE
error while running main file

### ISSUE THREAD

**Issue by phdumair** [shepardyan/Resilient-Reconfiguration-Problem-for-Distribution-Systems#1]
Hi, 

I am facing one problem while running main file

the error is 'define_constants' is not found in the current folder or on the MATLAB path,

I already downloaded matpower 7.1 and placed all provided files in matpower 

can you please tell whats wrong

**Comment by shepardyan** [comment]
First and foremost, thank you for your interest in this project!

The `define_constants` is a function from MATPOWER. If you are encountering the issue mentioned, it might be due to not correctly adding the MATPOWER code files to your MATLAB path. You can run the `install_matpower.m` file from the MATPOWER code package, and during installation, select the save path, which should then allow you to locate the `define_constants` function.
